### ISSUE TITLE
Generates two files not included in Ref folder

### ISSUE THREAD

**Issue by rbreslow** [neurolabusc/dcm_qa#9] opened 2024-02-08 20:37 UTC
```console
[nix-shell:~/projects/dcm_qa]$ dcm2niix --version
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC13.2.0 x86-64 (64-bit Linux)
v1.0.20230411

[nix-shell:~/projects/dcm_qa]$ ./batch.sh 
Cleaning output directory: /home/user/projects/dcm_qa/Out
Running command:
dcm2niix -b y -z n -f %p_%s -o /home/user/projects/dcm_qa/Out /home/user/projects/dcm_qa/In
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC13.2.0 x86-64 (64-bit Linux)
Found 105 DICOM file(s)
Image Decompression is new: please validate conversions
Warning: interpolated protocol 'noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_INTERP_AP' may be unsuitable for dwidenoise/mrdegibbs. /home/user/projects/dcm_qa/In/TotalReadoutTime/PF_PAT_POS_PFOV_PEres_INTERP_test2/NOPF_NOPAT_NOPOS_PERES100_ES0P59_BW2222_INTERP_AP_0028/PF_PAT_POS_BW_INTERP_TEST.MR.HEAD_HARMS.0028.0001.2017.09.20.16.16.44.39766.120168028.IMA
Warning: interpolated protocol 'noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_INTERP_PA' may be unsuitable for dwidenoise/mrdegibbs. /home/user/projects/dcm_qa/In/TotalReadoutTime/PF_PAT_POS_PFOV_PEres_INTERP_test2/NOPF_NOPAT_NOPOS_PERES100_ES0P59_BW2222_INTERP_PA_0029/PF_PAT_POS_BW_INTERP_TEST.MR.HEAD_HARMS.0029.0001.2017.09.20.16.16.44.39766.120172126.IMA
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW1112_AP_26 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres50_ES0p59_BW2222_AP_20 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/ax_int_36sl_12 (64x64x36x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/sag_int_35sl_24 (64x64x35x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/ax_asc_36sl_11 (64x64x36x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/ax_asc_36sl_9 (64x64x36x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW2222_AP_24 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/78PF_noPAT_noPOS_PEres100_ES0p59_BW2222_AP_18 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_50POS_PEres100_ES0p59_BW2222_PA_13 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_50POS_PEres100_ES0p59_BW2222_AP_12 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/cor_int_36sl_15 (64x64x36x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/ax_desc_36sl_10 (64x64x36x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres75_ES0p59_BW2222_PA_23 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_PA_9 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_200PFOV_AP_34 (90x180x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/sag_int_36sl_21 (64x64x36x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_p2_noPOS_PEres100_ES0p59_BW2222_AP_10 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_INTERP_PA_29 (180x180x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres75_ES0p59_BW2222_AP_22 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_AP_8 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/sag_asc_36sl_19 (64x64x36x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/58PF_noPAT_noPOS_PEres100_ES0p59_BW2222_PA_17 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/sag_asc_35sl_22 (64x64x35x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/cor_asc_35sl_16 (64x64x35x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_200PFOV_PA_35 (90x180x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_RL_30 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/cor_desc_36sl_14 (64x64x36x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_p4_noPOS_PEres100_ES0p59_BW2222_AP_32 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres50_ES0p59_BW2222_PA_21 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_INTERP_AP_28 (180x180x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_100POS_PEres100_ES0p59_BW2222_PA_15 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/sag_desc_35sl_23 (64x64x35x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/sag_desc_36sl_20 (64x64x36x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_LR_31 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/ax_desc_35sl_7 (64x64x35x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW2222_PA_25 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/78PF_noPAT_noPOS_PEres100_ES0p59_BW2222_PA_19 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/cor_desc_35sl_17 (64x64x35x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/58PF_noPAT_noPOS_PEres100_ES0p59_BW2222_AP_16 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/ax_int_35sl_8 (64x64x35x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/cor_int_35sl_18 (64x64x35x2)
CSA slice timing based on 2nd volume, 1st volume corrupted (CMRR bug, range 0..8.63999e+07, TR=3000 ms)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/fMRI_MB_int_26 (86x86x36x2)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW1112_PA_27 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_p2_noPOS_PEres100_ES0p59_BW2222_PA_11 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_noPAT_100POS_PEres100_ES0p59_BW2222_AP_14 (90x90x60x1)
Convert 1 DICOM as /home/user/projects/dcm_qa/Out/noPF_p4_noPOS_PEres100_ES0p59_BW2222_PA_33 (90x90x60x1)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/cor_asc_36sl_13 (64x64x36x2)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/ax_asc_35sl_6 (64x64x35x2)
CSA slice timing based on 2nd volume, 1st volume corrupted (CMRR bug, range 0..4880, TR=3000 ms)
Convert 2 DICOM as /home/user/projects/dcm_qa/Out/fMRI_MB_asc_25 (86x86x36x2)
Conversion required 0.446802 seconds (0.445930 for core code).



Validating JSON files.


/home/user/projects/dcm_qa/Out/58PF_noPAT_noPOS_PEres100_ES0p59_BW2222_AP_16.json  --  Valid.
/home/user/projects/dcm_qa/Out/58PF_noPAT_noPOS_PEres100_ES0p59_BW2222_PA_17.json  --  Valid.
/home/user/projects/dcm_qa/Out/78PF_noPAT_noPOS_PEres100_ES0p59_BW2222_AP_18.json  --  Valid.
/home/user/projects/dcm_qa/Out/78PF_noPAT_noPOS_PEres100_ES0p59_BW2222_PA_19.json  --  Valid.
/home/user/projects/dcm_qa/Out/ax_asc_35sl_6.json  --  Valid.
/home/user/projects/dcm_qa/Out/ax_asc_36sl_11.json  --  Valid.
/home/user/projects/dcm_qa/Out/ax_asc_36sl_9.json  --  Valid.
/home/user/projects/dcm_qa/Out/ax_desc_35sl_7.json  --  Valid.
/home/user/projects/dcm_qa/Out/ax_desc_36sl_10.json  --  Valid.
/home/user/projects/dcm_qa/Out/ax_int_35sl_8.json  --  Valid.
/home/user/projects/dcm_qa/Out/ax_int_36sl_12.json  --  Valid.
/home/user/projects/dcm_qa/Out/cor_asc_35sl_16.json  --  Valid.
/home/user/projects/dcm_qa/Out/cor_asc_36sl_13.json  --  Valid.
/home/user/projects/dcm_qa/Out/cor_desc_35sl_17.json  --  Valid.
/home/user/projects/dcm_qa/Out/cor_desc_36sl_14.json  --  Valid.
/home/user/projects/dcm_qa/Out/cor_int_35sl_18.json  --  Valid.
/home/user/projects/dcm_qa/Out/cor_int_36sl_15.json  --  Valid.
/home/user/projects/dcm_qa/Out/fMRI_MB_asc_25.json  --  Valid.
/home/user/projects/dcm_qa/Out/fMRI_MB_int_26.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_100POS_PEres100_ES0p59_BW2222_AP_14.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_100POS_PEres100_ES0p59_BW2222_PA_15.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_50POS_PEres100_ES0p59_BW2222_AP_12.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_50POS_PEres100_ES0p59_BW2222_PA_13.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_200PFOV_AP_34.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_200PFOV_PA_35.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_AP_8.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_INTERP_AP_28.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_INTERP_PA_29.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_PA_9.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_LR_31.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_RL_30.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW1112_AP_26.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW1112_PA_27.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW2222_AP_24.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres100_ES1p00_BW2222_PA_25.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres50_ES0p59_BW2222_AP_20.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres50_ES0p59_BW2222_PA_21.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres75_ES0p59_BW2222_AP_22.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_noPAT_noPOS_PEres75_ES0p59_BW2222_PA_23.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_p2_noPOS_PEres100_ES0p59_BW2222_AP_10.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_p2_noPOS_PEres100_ES0p59_BW2222_PA_11.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_p4_noPOS_PEres100_ES0p59_BW2222_AP_32.json  --  Valid.
/home/user/projects/dcm_qa/Out/noPF_p4_noPOS_PEres100_ES0p59_BW2222_PA_33.json  --  Valid.
/home/user/projects/dcm_qa/Out/sag_asc_35sl_22.json  --  Valid.
/home/user/projects/dcm_qa/Out/sag_asc_36sl_19.json  --  Valid.
/home/user/projects/dcm_qa/Out/sag_desc_35sl_23.json  --  Valid.
/home/user/projects/dcm_qa/Out/sag_desc_36sl_20.json  --  Valid.
/home/user/projects/dcm_qa/Out/sag_int_35sl_24.json  --  Valid.
/home/user/projects/dcm_qa/Out/sag_int_36sl_21.json  --  Valid.



Running command:
diff -x '.*' -br /home/user/projects/dcm_qa/Ref /home/user/projects/dcm_qa/Out -I ConversionSoftwareVersion
Only in /home/user/projects/dcm_qa/Out: fMRI_MB_int_26.json
Only in /home/user/projects/dcm_qa/Out: fMRI_MB_int_26.nii
```

**Comment by neurolabusc** [comment] 2024-02-08 21:32
Acknowledged. Current reference files are built without JPEG2000 support. By design, two of the input files are compressed using this transfer syntax. This issue will be fixed with the upcoming stable release.

**Closed as completed** 2024-02-16 18:09 UTC
Labels: acknowledged
